open-feature/go-sdk

TODO.md, go.mod, pkg/openfeature/evaluation_context.go, pkg/openfeature/openfeature.go, pkg/openfeature/provider.go
This is based in the feature provider interface described here:
https://github.com/open-feature/spec/blob/main/specification/provider/providers.md
=> Initial commit with feature provider interface

go.mod, go.sum, pkg/openfeature/client.go, pkg/openfeature/client_example_test.go, pkg/openfeature/client_test.go, pkg/openfeature/evaluation_context.go, pkg/openfeature/hooks.go, pkg/openfeature/hooks_mock_test.go, pkg/openfeature/hooks_test.go, pkg/openfeature/noop_provider.go, pkg/openfeature/openfeature.go, pkg/openfeature/openfeature_test.go, pkg/openfeature/provider.go, pkg/openfeature/provider_mock_test.go, pkg/openfeature/provider_test.go
https://github.com/open-feature/golang-sdk/issues/9
=> Hooks implementation

pkg/openfeature/client.go, pkg/openfeature/client_test.go, pkg/openfeature/noop_provider.go, pkg/openfeature/provider.go, pkg/openfeature/provider_mock_test.go, pkg/openfeature/provider_test.go
=> fix!: remove duplicate Value field from ResolutionDetail structs

pkg/openfeature/client.go, pkg/openfeature/client_test.go, pkg/openfeature/openfeature.go
=> fix: ensure default client logger is updated when global logger changes

README.md, go.mod, pkg/openfeature/client_example_test.go, pkg/openfeature/noop_provider_test.go, pkg/openfeature/provider.go
=> feat!: rename module to go-sdk

pkg/openfeature/client_test.go
=> feat: added test that ensures an error code is included in the evaluation details when the provider returns one

README.md, pkg/openfeature/client.go, pkg/openfeature/client_example_test.go, pkg/openfeature/client_test.go, pkg/openfeature/evaluation_context_test.go, pkg/openfeature/hooks_test.go, pkg/openfeature/noop_provider.go, pkg/openfeature/provider.go, pkg/openfeature/provider_mock_test.go, pkg/openfeature/provider_test.go
=> feat!: introduced context.Context to client and provider api

pkg/openfeature/client.go, pkg/openfeature/client_example_test.go, pkg/openfeature/client_test.go, pkg/openfeature/evaluation_context_test.go, pkg/openfeature/hooks_test.go, pkg/openfeature/openfeature.go
=> feat!: replaced EvaluationOptions with variadic option setter in client functions

.github/ISSUE_TEMPLATE/feature.yaml
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> chore: update link to ofep

README.md, pkg/openfeature/client.go, pkg/openfeature/client_test.go, pkg/openfeature/hooks_test.go, pkg/openfeature/noop_provider.go, pkg/openfeature/provider.go, pkg/openfeature/resolution_error.go
=> feat!: spec v0.5.0 compliance

pkg/openfeature/client.go, pkg/openfeature/client_test.go, pkg/openfeature/evaluation_context_test.go, pkg/openfeature/hooks.go, pkg/openfeature/hooks_mock_test.go, pkg/openfeature/hooks_test.go, pkg/openfeature/resolution_error.go
=> feat!: changed client details signatures to return new type

TODO.md
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> chore: remove outdated todo

README.md, pkg/openfeature/provider_test.go
- update a few tests whose associated spec numbers changed
- update spec badge
Closes: https://github.com/open-feature/go-sdk/issues/100
=> chore: update spec badge, test nums

README.md
adds openssf badge to readme
Fixes #37
=> chore: openssf badge

README.md
Add link to docsite from readme.
=> chore: add link to docsite

README.md
Introduces go reference doc badge to the readme
Fixes #107
=> chore: go reference doc badge

README.md
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> chore: document the release process

README.md
Include a link to the list of providers and hooks available.
Fixes #109
=> chore: add link to list of providers/hooks

renovate.json
Configures renovate to auto-merge minor/patch upgrades.
Imo, test coverage (unit & integration) is good enough to allow auto-merging.
Fixes #125
=> chore: configure renovate to auto-merge minor/patch upgrades

.github/workflows/release-please.yml, .goreleaser.yaml, README.md
Added sbom generation and push to release to the release workflow.
Fixes #126 
Tested in my forked repo.
=> chore: generate sbom

pkg/openfeature/provider.go
As per: https://github.com/open-feature/spec/blob/7ed7442c40d4e766424671258846b21a96adda70/specification/types.md#resolution-details
Signed-off-by: Todd Baert <toddbaert@gmail.com>
=> feat: add STATIC, CACHED reasons

README.md
- improves the copy used on the readme
- updates provider and hook links to use the ecosystem page
=> chore: update copy and links on the readme

README.md
Add details about state and eventing handling to readme
=> chore: adding state and eventing to readme

.goreleaser.yaml
Remove deprecated and unused go-releaser option.
=> fix: broken release process

Makefile
As in https://github.com/open-feature/go-sdk-contrib/pull/317/files#r1306174491
=> chore: fix golangci-lint version

README.md
=> fix: change typo in readme

README.md
- use `SetProviderAndWait` as the default provider setter in the README example
Fixes N/A
=> docs: Use `SetProviderAndWait` in README example

openfeature/telemetry/telemetry.go, openfeature/telemetry/telemetry_test.go
Update telemetry package to conform to latest spec. I also refactored a bit and added doc comments.
Fixes #364
=> feat: update telemetry package to conform to latest spec

e2e/evaluation_test.go
PR #336 requires manual intervention since the path to the gherkin file was changed.
=> chore: update test-harness

README.md, e2e/common_test.go, openfeature/client.go, openfeature/interfaces.go, openfeature/interfaces_mock.go, openfeature/memprovider/in_memory_provider.go, openfeature/memprovider/in_memory_provider_test.go, openfeature/noop_provider.go, openfeature/openfeature_api.go, openfeature/provider.go, openfeature/provider_mock.go, openfeature/provider_test.go, openfeature/testing/testprovider.go
=> refactor: use `evalCtx` and `flatCtx` consistently
