pkg/openfeature/evaluation_context.go
pkg/openfeature/openfeature.go
pkg/openfeature/provider.go
pkg/providers/noop.go

This implements the required interface and returns default values when invoked.

Add NoopProvider to test feature provider interface

---

pkg/openfeature/client.go

[Requirement 147 of the spec says that the error code must be provided upon abnormal execution](https://docs.openfeature.dev/docs/specification/sections/flag-evaluation#requirement-147). The current setup returns an `EvaluationDetails` with no error code, regardless of what error code the Provider returned.
This populates the `ResolutionDetail` of the return value with the error code, reason, and variant values returned by the provider.
Since this just populates the `ResolutionDetail` and not the `InterfaceResolutionDetail`, the default treatment will remain the value regardless of what the provider returned.

fix: return error code from client given by provider

---

pkg/openfeature/provider.go

Adding const for SPLIT reason.

fix: add reason indicating pseudorandom split

---

pkg/openfeature/client_test.go

- adds tests for 1.4.2, 1.4.5, 1.4.6
@rgrassian-split found this issue, this is just improving the tests around it. It added assertions for `reason` and `variant` and tests for all resolvers.
When Robert's fix is removed, all these tests fail:
```
--- FAIL: TestRequirement_1_4_2__1_4_5__1_4_6 (0.00s)
--- FAIL: TestRequirement_1_4_2__1_4_5__1_4_6/BooleanValueDetails (0.00s)
client_test.go:189: <nil>
--- FAIL: TestRequirement_1_4_2__1_4_5__1_4_6/StringValueDetails (0.00s)
client_test.go:199: Incorrect value returned!
--- FAIL: TestRequirement_1_4_2__1_4_5__1_4_6/FloatValueDetails (0.00s)
client_test.go:215: Incorrect value returned!
--- FAIL: TestRequirement_1_4_2__1_4_5__1_4_6/IntValueDetails (0.00s)
client_test.go:231: Incorrect value returned!
--- FAIL: …
```

chore: add 1.4.2, 1.4.5, 1.4.6 tests

---

pkg/openfeature/logger.go
pkg/openfeature/provider.go
pkg/openfeature/resolution_error.go

Adds the error message to the formatted error string. 
Makes it clear when logged that the error originates from the OpenFeature SDK.
Fixes #94

fix: resolution error only includes the code

---

pkg/openfeature/client.go
pkg/openfeature/client_test.go

Allow using a `nil` value when calling the `ObjectValueDetails` method.
Fixes #117

fix: authorize nil value for object evaluation

---

pkg/openfeature/hooks.go

- adds `HookContext` constructor
In order to properly unit test a `Hook` there must be some way of constructing a `HookContext` so that the `Before`, `After`, `Finally` and `Error` methods can be invoked directly.
Adding the constructor allows for the fields to remain unexpected and immutable, whilst also allowing for proper hook testing without an abstraction layer.

feat: HookContext constructor

---

pkg/openfeature/client.go

Signed-off-by: James Milligan <james@omnant.co.uk>
- adds `ClientMetadata` constructor
https://github.com/open-feature/go-sdk/pull/130
this pr added a constructor for `HookContext`, however, ClientMetadata contains the unexported field `name` and as such cannot be set in hook unit tests external to this package.

feat: NewClientMetadata constructor 

---

integration/caching_test.go

Stops attempt to load testing-flags.json in unit testing.

chore: strictly load testing-flags.json when needed

---

README.md
go.mod
go.sum
integration/evaluation_fuzz_test.go
pkg/openfeature/client.go

- Fuzzing tests.
- Validate that a flag key is valid UTF-8 (issue arose from fuzzing 🎉 )
Fixes #127

fix: validate that a flag key is valid UTF-8 & implemented fuzzing tests

---

CONTRIBUTING.md
Makefile
e2e/caching_test.go
e2e/evaluation_fuzz_test.go
e2e/evaluation_test.go

As has been brought up a few times, "end-to-end" is probably a better term for these tests, since they startup multiple processes and do inter-process communication streams with real (not mocked) artifacts.
No functional changes. I did use git mv to try to preserve history as best as possible.

chore: rename integration tests e2e

---

pkg/openfeature/client.go
pkg/openfeature/client_test.go
pkg/openfeature/provider.go

- implement flag metadata: https://github.com/open-feature/spec/commit/74c373e089ad77bf8cac84f3d93c00c945ff3a8a
https://github.com/open-feature/go-sdk/issues/177
If the flag metadata is not in the provider response, then the returned evaluation details will have a nil value, this can be updated to have an empty map, but IMO its a cleaner implementation to leave this value as nil ([nil slices have length 0](https://go.dev/play/p/_m0EwwCvJ65))

feat: add flag metadata field

---

pkg/openfeature/evaluation_context.go
pkg/openfeature/evaluation_context_test.go

Based on this [discussion](https://github.com/open-feature/go-sdk/pull/193#discussion_r1276491478) we have discovered that in some cases we want to create an EvaluationContext without Targeting key.
With`NewEvaluationContext` it was mandatory to set a `targetingKey` forcing us to set an empty `targetingKey` sometimes.
In this PR we add a new constructor called `NewTargetlessEvaluationContext` that is doing exactly the same things as `NewEvaluationContext` but does not force you to add a `targetingKey`.

feat: EvaluationContext add constructor without TargetingKey

---

e2e/evaluation_fuzz_test.go
e2e/evaluation_test.go
pkg/openfeature/evaluation_context_test.go
pkg/openfeature/hooks_test.go
pkg/openfeature/memprovider/in_memory_provider.go
pkg/openfeature/memprovider/in_memory_provider_test.go
pkg/openfeature/openfeature_test.go

Sorts imports of go files by running command on root directory.
```
~/go-sdk goimports -w .
```
N/A
In VSCode settings.json
```
...
"[go]": {
"editor.formatOnSave": true,
"editor.codeActionsOnSave": {
"source.organizeImports": true
},
},
...
```
Also results in it sorts the imports every time onSave.
Probably we can setup pre-merge check or pre-commit for go format and lint.
N/A

chore: sort imports of go files

---

pkg/openfeature/api.go
pkg/openfeature/openfeature.go
pkg/openfeature/openfeature_test.go

Update comments for named provider related functions.
N/A
Only updates comments.
N/A
N/A

chore: update comments for named provider related function

---

pkg/openfeature/event_executor.go
pkg/openfeature/event_executor_test.go
pkg/openfeature/provider.go

Add a stale state and ensure event handlers run immediately if the associated provider and the state associated with the handle are compatible.
Resolves #220.

feat: run event handlers immediately, add STALE (0.7.0 compliance)

---

README.md

Bump spec badge in readme to v0.7.0.
Closes #217.

chore: bump spec badge in readme to v0.7.0

---

.github/workflows/pr-checks.yml

- revert to CodeCov Action to v3
There's an ongoing issue with v4.
https://github.com/codecov/codecov-action/issues/1087

chore: revert to CodeCov Action to v3

---

README.md

- fix logo rendering outside of github
Addresses the logo not showing up in the Go registry.
https://pkg.go.dev/github.com/open-feature/go-sdk#section-readme
Update the org level template.

chore: fix logo rendering outside of github

---

pkg/openfeature/client.go

Rewrite all the [T]Value functions in terms of [T]ValueDetails functions to reduce duplication. [T]ValueDetails is not anything significantly much more than [T]Details.
By the way, I noticed this while I was looking at the code to see if it could be genericizied (#158) and it seems like it can, but it is a bit tricky I think.

refactor: write [T]Value in terms of [T]ValueDetails

---

openfeature/event_executor.go
openfeature/event_executor_test.go
openfeature/provider.go

Contains minor improvements on the eventing of the SDK
- Expose the provider name from `EventDetails`
- Add buffer to internal channel handler to improve concurrency: Buffer should theoretically allow us to handle events in order of they are received

chore: improve eventing

---

openfeature/api.go
openfeature/event_executor.go
openfeature/event_executor_test.go
openfeature/openfeature.go
openfeature/openfeature_test.go

- Add `SetProviderAndWait` & `SetNamedProviderAndWait` with blocking provider mutators
- Improve non-eventing provider registration by emitting ready event : This can be considered as a fix as this is defined in spec but was missing in the implementation [^1]
> The provider MAY define a status field/accessor which indicates the readiness of the provider, with possible values NOT_READY, READY, STALE, or ERROR.
> Providers without this field can be assumed to be ready immediately.
Fixes #240
Tests were added to cover new APIs and old tests were updated to handle readiness emitted for non eventing providers 
[^1]: https://openfeature.dev/specification/sections/providers#requirement-242

feat: blocking provider mutator

---

.github/workflows/release-please.yml
README.md
go.mod
go.sum

Update Go version from `1.18` to `1.19`. 
Go 1.22 rc2 is alrady out and this is an attempt to gradually upgrade to go 1.20, keeping support for the last two major versions.

feat: update to go 1.19

---

openfeature/client.go
openfeature/client_example_test.go

- adds new client methods `Boolean`, `String`, `Float`, `Int`, and `Object` that enable simpler usage (no error handling required)
Fixes #262
There seems to be a soft consensus on #262, so this may need to change if the TC deems necessary, but I'm submitting this early for discussion's sake.
See additional examples provided.

feat: Adding simplified evaluation methods

---

.github/workflows/pr-checks.yml
.github/workflows/release-please.yml
README.md
go.mod
go.sum

Fixes https://github.com/open-feature/go-sdk/issues/253

chore: bump Go to version 1.20

---

README.md

The old link referenced deprecated paths.

docs: update Go package manager link

---

.github/workflows/pr-checks.yml
.github/workflows/release-please.yml
go.mod

Require go 1.21.
1.20 has long been EOL: https://endoflife.date/go
This is consistent with our guidelines on runtime support.

chore: require go 1.21

---

.github/workflows/pr-checks.yml

Fixes publishing test coverage results to Codecov.
The coverage results are now saved in two separate files, `coverage-unit.out` and `coverage-e2e.out`, preventing any overwrites during the execution of the two test suites. Additionally, each result is uploaded to Codecov separately, with distinct flags to logically differentiate them.
fixes  #304
https://app.codecov.io/github/open-feature/go-sdk/tree/warber%2Fgo-sdk%3Atest%2Ffix-codecov-upload/openfeature

chore: fix coverage uploads to Codecov

---

openfeature/client.go
openfeature/event_executor.go
openfeature/openfeature.go
openfeature/openfeature_test.go
pkg/openfeature/client.go
pkg/openfeature/openfeature.go

This PR ensures consistent usage of the term "domain" throughout the codebase, replacing instances of "name," "clientName," and similar terms.

chore: use correct term "domain" instead of name/clientName in code

---

openfeature/client.go
openfeature/client_test.go
openfeature/event_executor.go
openfeature/event_executor_test.go
openfeature/openfeature_test.go

fix: consider default client when loading states

---

README.md

This PR includes an entry for the 'tracking' feature in the feature table of the `README.md` file.

docs: add missing entry for "tracking" in feature table

---

CONTRIBUTING.md

This PR adds the commit convention to the CONTRIBUTING docs. This caught me out on https://github.com/open-feature/go-sdk/pull/320, hopefully this helps the next person!

docs: add PR title and DCO rules to CONTRIBUTING.md

---

go.mod
go.sum
openfeature/event_executor.go
openfeature/event_executor_test.go
openfeature/openfeature_api.go

The exp module does not have the same compatibility guarantees as the standard library. The fact that it stays on a pseudo-version instead of a proper semver tag, and the possibility for backwards-incompatible changes, makes depending on exp in a widely-imported library a bit risky. If a dependent of the SDK updated the version of exp they relied on, the MVS algorithm could select a version that broke the SDK's usage of exp's packages.
Out of an abundance of caution, I'm trying to reduce the use of exp in our private shared libraries for this reason, and the OpenFeature SDK is our only external dependency that depends on it it. The uses are pretty small. I've replaced them with existing standard library functiosn where possible, or in one place implemented the functionality myself, since …

refactor: remove dependency on golang.org/x/exp

---

README.md

There is a discrepancy between the default provider registration function in the [docs on openfeature.dev](https://openfeature.dev/docs/tutorials/getting-started/go) and in the `README` of this repository. Since `SetProvider` is async, it makes more sense to default to using `SetProviderAndWait` in all documentation uniformly.
- updates the `README` to use `SetProviderAndWait` as the default registration function
Fixes N/A

docs: Use `SetProviderAndWait` in README

---

openfeature/openfeature_test.go
openfeature/testing/testprovider_test.go

Fix tests: add missing cleanup and wait.
Missing cleanup caused test failures if the tests are executed in a different order.
Missing wait caused issues when the provider wasn't initializes before the test executed.

test: fix tests - add missing cleanup and wait.

---

openfeature/client.go
openfeature/interfaces.go
openfeature/openfeature.go
openfeature/openfeature_api.go

Correctly deprecate identifiers so that the pkgsite documentation hides the deprecated identifiers. Also use Go doc comment "doc links" to refer to exported identifiers.
https://tip.golang.org/doc/comment
Fixes #346 
You may see a few additional formatting changes that were made because I have my editor setup to run gofumpt on save.
```sh
make docs
```

docs: deprecate identifiers correctly

---

README.md
e2e/common_test.go
e2e/evaluation_fuzz_test.go
e2e/evaluation_test.go
openfeature/client.go
openfeature/client_test.go
openfeature/evaluation_context.go
openfeature/evaluation_context_test.go
openfeature/event_executor_test.go
openfeature/hooks.go
openfeature/hooks/logging_hook.go
openfeature/hooks/logging_hook_test.go
openfeature/hooks_test.go
openfeature/interfaces.go
openfeature/memprovider/in_memory_provider.go
openfeature/memprovider/in_memory_provider_test.go
openfeature/noop_provider.go
openfeature/openfeature_test.go
openfeature/provider.go
openfeature/provider_test.go
openfeature/reference.go
openfeature/testing/testprovider.go
pkg/openfeature/evaluation_context.go
pkg/openfeature/hooks.go
pkg/openfeature/provider.go

Replace usage of `interface{}` with `any`.
This is a stylistic update only. See issue #358 for details.
Fixes #358

style: replace usage of `interface{}` with `any`

---

openfeature/hooks/logging_hook.go
openfeature/hooks/logging_hook_test.go

- add go doc comments
- add a `stage` key to the logs as per [the spec](https://openfeature.dev/specification/appendix-a#logging-hook)
- ensure LoggingHook method receivers are all named `h` (the `buildArgs` method had a receiver named `l`)
- use consistent parameter names for the Before, After, Error, and Finally methods
- simplify the `buildArgs` method by removing the error return parameter
- use [slog.Attr](https://pkg.go.dev/log/slog#Attr) instead of `interface{}` types to log attributes
- the above allows the use of [Logger.LogAttrs](https://pkg.go.dev/log/slog#Logger.LogAttrs), which is [the most efficient form of log output](https://pkg.go.dev/log/slog#Logger.LogAttrs:~:text=For%20the%20most%20efficient,ctx%2C%20%22hello%22%2C%20%22count%22%2C%203)
- as a consequence of the above, …

refactor: simplify and improve logging hook

---

.golangci.yml
openfeature/hooks/logging_hook_test.go
openfeature/memprovider/in_memory_provider_test.go
openfeature/provider.go
openfeature/resolution_error.go

Add the misspell and dupword linters to catch typos. Misspell checks for common misspellings and dupword checks for duplicate consecutive words like "the the".
Also ran `make fix` to auto-fix all the findings.
https://golangci-lint.run/usage/linters/

chore: add `misspell` and `dupword` linters

---

openfeature/openfeature_test.go

Fix data race condition in the test. Instead of waiting for 200 ms block the initialization.

test: fix data race condition

---

openfeature/hooks/logging_hook.go
openfeature/hooks/logging_hook_test.go

Building on #361, the logging hook implementation could use additional improvement. Note that all 4 issues are breaking changes, but since hooks are considered experimental, I think it is acceptable.
- Log key consts are now camelCase and unexported.
- The NewLoggingHook function now requires the user to pass in a logger and NewCustomLoggingHook has been removed. It is very easy for a user to get the old behaviour by simply using `hooks.NewLoggingHook(true, slog.Default())` instead of `hooks.NewLoggingHook(true)`.
- The MarshaledEvaluationContext struct has been removed because it was unnecessary and created PascalCase output for the nested keys.
- The NewLoggingHook no longer returns an error, making initialization simpler for the user as they no longer have to check for an error that …

feat!: simplify and improve logging hook

---

README.md

By convention, it is a good idea to use context.TODO() in examples instead of context.Background() in example code to indicate to the reader that these should be updated. 
https://pkg.go.dev/context#TODO

docs: use `context.TODO()` in README examples

---

codecov.yml

This will allow for mocks in any folder to be ignored rather than just in the `openfeature` package. This will unblock #354 
Unblocks #354
I added new mocks in another PR, however the ignore path only for coverage only specifies the `openfeature` package for mocks. Since I introduced new mocks in another package the coverage percentage dropped below the allowed threshold blocking my PR.
Nada
Not applicable

build: Use a less restrictive glob pattern to ignore mocks in coverage

---

.golangci.yml
e2e/evaluation_fuzz_test.go
openfeature/client_test.go
openfeature/event_executor_test.go
openfeature/hooks_test.go
openfeature/noop_provider.go
openfeature/openfeature_test.go
openfeature/provider.go
openfeature/reference_test.go
openfeature/testing/testprovider_test.go
openfeature/util_test.go

Enable both gofumpt (instead of gofmt) and gci formatters. Gofumpt is a bit stricter than gofmt, allowing us to standardize formatting even further. The gci formatter ensures that import statements are sorted and grouped deterministically in a consistent manner.
https://golangci-lint.run/usage/formatters/

chore: enable gofumpt and gci

---

README.md
openfeature/client_test.go
openfeature/provider.go

This PR removes the Status() method from the provider.
Related to #299

fix: remove Status method from provider

---

openfeature/client_test.go
openfeature/evaluation_context_test.go
openfeature/event_executor_test.go
openfeature/hooks_test.go
openfeature/openfeature_test.go

The `defer` is redundant, because `t.Cleanup` already ensures that the function is not called until after the test is done.
https://pkg.go.dev/testing#T.Cleanup
> Cleanup registers a function to be called when the test (or subtest) and all its subtests complete. Cleanup functions will be called in last added, first called order.

test: don't defer t.Cleanup

---

README.md
go.mod
go.sum

- set the minimum required Go version to 1.24.0
Closes #419

chore: upgrade go from 1.23 to 1.24
